# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python package

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: 3.x
    - name: Install Node
      uses: actions/setup-node@v1
      with:
        node-version: '10'
    - name: Install slither
      run: |
        git clone https://github.com/crytic/slither.git
        cd slither
        python setup.py install

    - name: Install solidity
      run: |
        sudo add-apt-repository ppa:ethereum/ethereum
        sudo apt-get update
        sudo apt-get install solc
    - name: Install NPM packages
      run: npm install
    - name: Analyze contracts
      run: slither . --filter-paths Test
